{{- if .Values.ssh.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "jupyterhub-ssh.ssh.fullname" . }}
  labels:
    {{- include "jupyterhub-ssh.ssh.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "jupyterhub-ssh.ssh.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # FIXME: This is way too permissive
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
  ingress:
  # Allow pods in the same namespace with this label to have network access
  - from:
    - podSelector:
        matchLabels:
          hub.jupyter.org/network-access-ssh-server: "true"
    ports:
      - port: ssh
        protocol: TCP
{{- end }}
